### ISSUE TITLE
undefined function simplexml_load_file()

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/csl-pywork#29]
Some missing function in PHP code for display?
I get the following error in my error.log file.
```
[Sun Sep 12 17:20:51.625650 2021] [php7:error] [pid 806] [client 127.0.0.1:35378] PHP Fatal error:  Uncaught Error: Call to undefined function simplexml_load_file() in /var/www/html/cologne/mw/web/utilities/transcoder.php:41\nStack trace:\n#0 /var/www/html/cologne/mw/web/utilities/transcoder.php(271): transcoder_fsm()\n#1 /var/www/html/cologne/mw/web/webtc2/query.php(72): transcoder_processString()\n#2 /var/www/html/cologne/mw/web/webtc2/query.php(33): construct_outputarr()\n#3 {main}\n  thrown in /var/www/html/cologne/mw/web/utilities/transcoder.php on line 41, referer: http://localhost/cologne/mw/web/webtc2/index.php
[Sun Sep 12 17:20:56.009909 2021] [php7:error] [pid 809] [client 127.0.0.1:35380] PHP Fatal error:  Uncaught Error: Call to undefined function simplexml_load_file() in /var/www/html/cologne/mw/web/utilities/transcoder.php:41\nStack trace:\n#0 /var/www/html/cologne/mw/web/utilities/transcoder.php(271): transcoder_fsm()\n#1 /var/www/html/cologne/mw/web/webtc2/query.php(72): transcoder_processString()\n#2 /var/www/html/cologne/mw/web/webtc2/query.php(33): construct_outputarr()\n#3 {main}\n  thrown in /var/www/html/cologne/mw/web/utilities/transcoder.php on line 41, referer: http://localhost/cologne/mw/web/webtc2/index.php
[Sun Sep 12 17:21:14.314520 2021] [php7:error] [pid 1405] [client 127.0.0.1:35382] PHP Fatal error:  Uncaught Error: Call to undefined function simplexml_load_file() in /var/www/html/cologne/mw/web/utilities/transcoder.php:41\nStack trace:\n#0 /var/www/html/cologne/mw/web/utilities/transcoder.php(271): transcoder_fsm()\n#1 /var/www/html/cologne/mw/web/webtc2/query.php(72): transcoder_processString()\n#2 /var/www/html/cologne/mw/web/webtc2/query.php(33): construct_outputarr()\n#3 {main}\n  thrown in /var/www/html/cologne/mw/web/utilities/transcoder.php on line 41, referer: http://localhost/cologne/mw/web/webtc2/index.php
```

**Comment by drdhaval2785** [comment]
I do not know if I ever will use this script. Closing this issue.
